-- Created by Vertabelo (http://vertabelo.com)
-- Last modification date: 2017-03-17 21:12:58.907

-- foreign keys
ALTER TABLE HORARIOS
    DROP FOREIGN KEY HORARIOS_TIENDAS;

ALTER TABLE ITEMS_LISTA
    DROP FOREIGN KEY ITEMS_LISTA_ITEMS;

ALTER TABLE ITEMS_LISTA
    DROP FOREIGN KEY ITEMS_LISTA_USUARIOS;

ALTER TABLE ITEMS
    DROP FOREIGN KEY ITEMS_PRODUCTOS;

ALTER TABLE ITEMS
    DROP FOREIGN KEY ITEMS_TIENDAS;

ALTER TABLE LISTAS_MERCADOS
    DROP FOREIGN KEY LISTAS_MERCADOS_ITEMS_LISTA;

ALTER TABLE LISTAS_MERCADOS
    DROP FOREIGN KEY LISTAS_MERCADOS_USUARIOS;

ALTER TABLE OPINIONES
    DROP FOREIGN KEY OPINIONES_USUARIOS;

ALTER TABLE TENDEROS
    DROP FOREIGN KEY TENDEROS_TIENDAS;

ALTER TABLE TIENDAS
    DROP FOREIGN KEY TIENDAS_OPINIONES;

ALTER TABLE TIENDAS
    DROP FOREIGN KEY TIENDAS_TENDEROS;

ALTER TABLE USUARIOS_AUTENTICACION
    DROP FOREIGN KEY USUARIOS_AUTENTICACION_USUARIOS;

ALTER TABLE USUARIOS_ROLES
    DROP FOREIGN KEY USUARIOS_ROLES_USUARIOS;

ALTER TABLE TENDEROS
    DROP FOREIGN KEY USUARIOS_TENDEROS;

-- tables
DROP TABLE HORARIOS;

DROP TABLE ITEMS;

DROP TABLE ITEMS_LISTA;

DROP TABLE LISTAS_MERCADOS;

DROP TABLE OPINIONES;

DROP TABLE PRODUCTOS;

DROP TABLE TENDEROS;

DROP TABLE TIENDAS;

DROP TABLE USUARIOS;

DROP TABLE USUARIOS_AUTENTICACION;

DROP TABLE USUARIOS_ROLES;

-- End of file.

