-- Created by Vertabelo (http://vertabelo.com)
-- Last modification date: 2017-05-07 18:55:47.556

-- tables
-- Table: HORARIOS
CREATE TABLE HORARIOS (
    id int NOT NULL AUTO_INCREMENT,
    TIENDAS_id int NOT NULL,
    horaInicio int NOT NULL,
    horaFin int NOT NULL,
    minutosInicio int NOT NULL,
    minutosFin int NOT NULL,
    dia varchar(50) NOT NULL,
    CHECK (horaInicio>=0 AND horaInicio<=23),
    CHECK (horaFin>=0 AND horaFin<=23),
    CHECK (minutosInicio>=0 AND minutosInicio<=59),
    CHECK (minutosFin>=0 AND minutosFin<=59),
    CHECK (dia IN ('Lunes','Martes','Miercoles','Jueves','Viernes','Sabado','Domingo')),
    CHECK ((horaFin > hotaInicio) or (horaFin=horaInicio and minutosFin>minutosInicio)),
    CONSTRAINT HORARIOS_pk PRIMARY KEY (id)
);

-- Table: ITEMS
CREATE TABLE ITEMS (
    id int NOT NULL AUTO_INCREMENT,
    PRODUCTOS_id bigint NOT NULL,
    TIENDAS_id int NOT NULL,
    precio bigint NOT NULL,
    CHECK (precio>0),
    CONSTRAINT ITEMS_pk PRIMARY KEY (id)
);

-- Table: ITEMS_LISTA
CREATE TABLE ITEMS_LISTA (
    id int NOT NULL AUTO_INCREMENT,
    ITEMS_id int NOT NULL,
    LISTAS_MERCADOS_id int NOT NULL,
    comprado bool NOT NULL,
    favorito bool NOT NULL,
    CONSTRAINT ITEMS_LISTA_pk PRIMARY KEY (id)
);

-- Table: LISTAS_MERCADOS
CREATE TABLE LISTAS_MERCADOS (
    id int NOT NULL AUTO_INCREMENT,
    nombre varchar(100) NOT NULL,
    fechaCreacion timestamp NOT NULL,
    realizado bool NOT NULL,
    USUARIOS_id int NOT NULL,
    CONSTRAINT LISTAS_MERCADOS_pk PRIMARY KEY (id)
);

-- Table: OPINIONES
CREATE TABLE OPINIONES (
    id int NOT NULL AUTO_INCREMENT,
    comentario varchar(100) NOT NULL,
    gusta bool NOT NULL,
    fecha timestamp NOT NULL,
    USUARIOS_id int NOT NULL,
    TIENDAS_id int NOT NULL,
    CONSTRAINT OPINIONES_pk PRIMARY KEY (id)
);

-- Table: PRODUCTOS
CREATE TABLE PRODUCTOS (
    id bigint NOT NULL AUTO_INCREMENT,
    nombre varchar(100) NOT NULL,
    marca varchar(100) NOT NULL,
    imagen blob NULL,
    categoria varchar(100) NOT NULL,
    CONSTRAINT PRODUCTOS_pk PRIMARY KEY (id)
);

-- Table: TENDEROS
CREATE TABLE TENDEROS (
    USUARIOS_id int NOT NULL,
    TIENDAS_id int NOT NULL,
    CONSTRAINT TENDEROS_pk PRIMARY KEY (USUARIOS_id)
);

-- Table: TIENDAS
CREATE TABLE TIENDAS (
    id int NOT NULL AUTO_INCREMENT,
    direccion varchar(100) NOT NULL,
    x double(100,10) NOT NULL,
    y double(100,10) NOT NULL,
    nombre varchar(100) NOT NULL,
    nit varchar(100) NOT NULL,
    telefono varchar(100) NOT NULL,
    disponible bool NOT NULL,
    logo blob NULL,
    CONSTRAINT TIENDAS_pk PRIMARY KEY (id)
);

-- Table: USUARIOS
CREATE TABLE USUARIOS (
    id int NOT NULL AUTO_INCREMENT,
    correo varchar(100) NOT NULL,
    nombre varchar(100) NOT NULL,
    UNIQUE INDEX USUARIOS_ak_1 (correo),
    CONSTRAINT USUARIOS_pk PRIMARY KEY (id)
);

-- Table: USUARIOS_AUTENTICACION
CREATE TABLE USUARIOS_AUTENTICACION (
    USUARIOS_id int NOT NULL,
    hash varchar(70) NOT NULL,
    habilitado bool NOT NULL DEFAULT true,
    rol varchar(100) NOT NULL,
    CONSTRAINT USUARIOS_AUTENTICACION_pk PRIMARY KEY (USUARIOS_id)
);

-- foreign keys
-- Reference: HORARIOS_TIENDAS (table: HORARIOS)
ALTER TABLE HORARIOS ADD CONSTRAINT HORARIOS_TIENDAS FOREIGN KEY HORARIOS_TIENDAS (TIENDAS_id)
    REFERENCES TIENDAS (id);

-- Reference: ITEMS_LISTA_ITEMS (table: ITEMS_LISTA)
ALTER TABLE ITEMS_LISTA ADD CONSTRAINT ITEMS_LISTA_ITEMS FOREIGN KEY ITEMS_LISTA_ITEMS (ITEMS_id)
    REFERENCES ITEMS (id);

-- Reference: ITEMS_LISTA_LISTAS_MERCADOS (table: ITEMS_LISTA)
ALTER TABLE ITEMS_LISTA ADD CONSTRAINT ITEMS_LISTA_LISTAS_MERCADOS FOREIGN KEY ITEMS_LISTA_LISTAS_MERCADOS (LISTAS_MERCADOS_id)
    REFERENCES LISTAS_MERCADOS (id);

-- Reference: ITEMS_PRODUCTOS (table: ITEMS)
ALTER TABLE ITEMS ADD CONSTRAINT ITEMS_PRODUCTOS FOREIGN KEY ITEMS_PRODUCTOS (PRODUCTOS_id)
    REFERENCES PRODUCTOS (id);

-- Reference: ITEMS_TIENDAS (table: ITEMS)
ALTER TABLE ITEMS ADD CONSTRAINT ITEMS_TIENDAS FOREIGN KEY ITEMS_TIENDAS (TIENDAS_id)
    REFERENCES TIENDAS (id);

-- Reference: LISTAS_MERCADOS_USUARIOS (table: LISTAS_MERCADOS)
ALTER TABLE LISTAS_MERCADOS ADD CONSTRAINT LISTAS_MERCADOS_USUARIOS FOREIGN KEY LISTAS_MERCADOS_USUARIOS (USUARIOS_id)
    REFERENCES USUARIOS (id);

-- Reference: OPINIONES_TIENDAS (table: OPINIONES)
ALTER TABLE OPINIONES ADD CONSTRAINT OPINIONES_TIENDAS FOREIGN KEY OPINIONES_TIENDAS (TIENDAS_id)
    REFERENCES TIENDAS (id);

-- Reference: OPINIONES_USUARIOS (table: OPINIONES)
ALTER TABLE OPINIONES ADD CONSTRAINT OPINIONES_USUARIOS FOREIGN KEY OPINIONES_USUARIOS (USUARIOS_id)
    REFERENCES USUARIOS (id);

-- Reference: TENDEROS_TIENDAS (table: TENDEROS)
ALTER TABLE TENDEROS ADD CONSTRAINT TENDEROS_TIENDAS FOREIGN KEY TENDEROS_TIENDAS (TIENDAS_id)
    REFERENCES TIENDAS (id);

-- Reference: USUARIOS_AUTENTICACION_USUARIOS (table: USUARIOS_AUTENTICACION)
ALTER TABLE USUARIOS_AUTENTICACION ADD CONSTRAINT USUARIOS_AUTENTICACION_USUARIOS FOREIGN KEY USUARIOS_AUTENTICACION_USUARIOS (USUARIOS_id)
    REFERENCES USUARIOS (id);

-- Reference: USUARIOS_TENDEROS (table: TENDEROS)
ALTER TABLE TENDEROS ADD CONSTRAINT USUARIOS_TENDEROS FOREIGN KEY USUARIOS_TENDEROS (USUARIOS_id)
    REFERENCES USUARIOS (id);

-- End of file.

